### ISSUE TITLE
How to set timezone

### ISSUE THREAD

**Issue by AliMoeen** [extrange/ibkr-docker#103]
Hi Folks, 

Would would be the easiest way to set the timezone for IB Gateway?

Thank you,

**Comment by extrange** [comment]
You can do it in `compose.yml` e.g.

```yml
#...
    environment:
      TZ: Asia/Singapore
```
