### ISSUE TITLE
Cannot connect from a remote server

### ISSUE THREAD

**Issue by smjure** [extrange/ibkr-docker#108]
First of all, thank you for the package 🙏

I'm using Gateway on a remote server, live session. If I run IBKRs Gateway software, all works fine. I could not replace it with your `ibkr-docker`, although I'd like to in order to be headless. Using `ibkr-docker` I do login sucessfully via authentication, but when running the remote app, it does not connect, so I assume it must be sth with IPs and/or ports. This is my `compose.yml` file:
```
services:
  ibkr:
    image: ghcr.io/extrange/ibkr  # latest, stable, 10.21, 10.21.1p etc
    ports:
      - "0.0.0.0:4001:4001"  # API access
    ulimits:
      nofile: 10000  # See FAQ
    environment:
      USERNAME: ${USERNAME}  # Ensure these are set in your environment or .env file
      PASSWORD: ${PASSWORD}  # Ensure these are set in your environment or .env file
      GATEWAY_OR_TWS: gateway
      IBC_TradingMode: live
      IBC_ReadOnlyApi: 'no'
      TrustedTwsApiClientIPs: 1xy.11.1.xy,1xy.98.18.zx
```
I saw #52 and #105, but couldn't help with it. One thing comes to my mind is, that in the IBKR Gateway Software, I had to specify the trusted IPs to make it work, which I also did as above, but for some reason does not work.
![2024-07-19_11-23](https://github.com/user-attachments/assets/a8bbf623-9624-4b6e-b398-5671b15e3b87)

Please any suggestions? 🙏
