### ISSUE TITLE
10.34.1a image connection failure

### ISSUE THREAD

**Issue by Ashourism** [extrange/ibkr-docker#114]
I have this simple docker file that part of my workflow
```
services:
  ibkr:
    container_name: ibkr
    image: ghcr.io/extrange/ibkr
    ulimits:
      nofile: 10000
    environment:
      USERNAME: ${xx}
      PASSWORD: ${xx}
    ports:
      - "127.0.0.1:8888:8888"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G 
        reservations:
          memory: 3G
```

 since you pushed the latest image ibkr:10.34.1a - yesterday as I see here https://github.com/extrange/ibkr-docker/pkgs/container/ibkr

I can not connect with my workflow to IBKR anymore and in the docker container I keep getting this issue

```
ibkr  | 2025/02/06 14:55:19 socat[11] N forked off child process 186
ibkr  | 2025/02/06 14:55:19 socat[11] N listening on AF=2 0.0.0.0:8888
ibkr  | 2025/02/06 14:55:19 socat[11] N childdied(): handling signal 17
ibkr  | 2025/02/06 14:55:19 socat[11] N accepting connection from AF=2 xx.xx.xx.xx:43448 on AF=2 xx.xx.xx.xx:8888
ibkr  | 2025/02/06 14:55:19 socat[11] N forked off child process 187
ibkr  | 2025/02/06 14:55:19 socat[11] N listening on AF=2 0.0.0.0:8888
ibkr  | 2025/02/06 14:55:19 socat[187] N opening connection to AF=2 127.0.0.1:7496
ibkr  | 2025/02/06 14:55:19 socat[187] W recvmsg(): Resource temporarily unavailable
ibkr  | 2025/02/06 14:55:19 socat[187] E connect(5, AF=2 127.0.0.1:7496, 16): Connection refused
ibkr  | 2025/02/06 14:55:19 socat[187] N exit(1)
```

The xx.xx.xx.xx is the ip-address of another docker container running in host mode

Switching back to version 10.33 mitigates this error

```
services:
  ibkr:
    container_name: ibkr 
    image: ghcr.io/extrange/ibkr:10.33
    ulimits:
      nofile: 10000
    environment:
      USERNAME: ${xx}
      PASSWORD: ${xx}
    ports:
      - "127.0.0.1:8888:8888"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"  # 2 cores
          memory: 4G
        reservations:
          memory: 3G
```

The client container uses python with ib_insync

Would be great if you can look into this
