### ISSUE TITLE
Unable to Open Settings Dialog in IBKR Gateway via noVNC

### ISSUE THREAD

**Issue by volcanomao** [extrange/ibkr-docker#117]
I am experiencing an issue with the IBKR Gateway when accessed via noVNC. Specifically, clicking on the "Configure" settings button does not open the settings dialog as expected.

System Details:

Gateway Version: Build 10.34.1c Feb 13, 2025 4:03:19 PM

Docker Image: ghcr.io/extrange/ibkr:latest

docker-compose.yml Configuration:
```
services:
  ibkr:
    image: ghcr.io/extrange/ibkr # latest, stable, 10.21, 10.21.1p etc
    ports:
      - "127.0.0.1:6080:6080" # noVNC browser access
      - "127.0.0.1:7497:8888" # API access
    ulimits:
      nofile: 10000 # See FAQ
    environment:
      USERNAME: ${IBKR_PAPER_USERNAME} # Set in environment variables
      PASSWORD: ${IBKR_PAPER_PASSWORD} # Set in environment variables

      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: gateway #tws

      TZ='US/Eastern'
      # Variables prefixed with IBC_ override IBCAlpha's config.ini:
      IBC_TradingMode: paper #live
      IBC_ReadOnlyApi: 'no' #yes
      IBC_AutoRestartTime: "07:00 AM"
      IBC_ColdRestartTime: "08:00 AM"
      IBC_AcceptNonBrokerageAccountWarning: 'yes'
      TWS_SETTINGS_PATH: /settings
    volumes:
      - ./settings:/settings:rw
```
Issue Details:

The IBKR Gateway launches successfully and is accessible via noVNC.

Other UI interactions seem to work correctly.

Clicking on the "Configure" settings button does nothing (no dialog appears).

Check the logs and note that there is no output when clicking the "Settings" menu.
No relevant error messages are observed in the logs.

Additional Information:

I have tried restarting the container, but the issue persists.

The issue occurs with the latest version of the IBKR Gateway in the provided Docker image.

Any insights or solutions would be appreciated. Thank you!
