### ISSUE TITLE
Cannot connect to TWS API

### ISSUE THREAD

**Issue by katanisk8** [extrange/ibkr-docker#16]
Hi

My docker-compose setup of TWS:

![image](https://user-images.githubusercontent.com/23279273/230391423-8e287004-4e22-4c61-ae37-840e5f18bf70.png)

Container is successfully created and I can open TWS and see trades etc:

![image](https://user-images.githubusercontent.com/23279273/230393609-e852691e-a1b6-4583-8c2b-ad54f443a85c.png)

I'm trying connect to TWS using provided EClientSocket from TWS API. Using host: ikbr, port: 8888 (tried use host as localhost, 127.0.0.1, host.docker.internal etc. nothing helped):

![image](https://user-images.githubusercontent.com/23279273/230394698-6d3b268b-57f9-4035-89ad-afb517b0d6fc.png)

I am not getting any error but IsConnected() method at line 42 all time returning me false.

In ikbr container logs I can see thet connection to 127.0.0.1:7496 is refused:

![image](https://user-images.githubusercontent.com/23279273/230393283-a674394c-10f8-4cf2-898d-7d755fa48e15.png)

What I'm doing wrong?

**Comment by extrange** [comment]
Try adding `IBC_AcceptIncomingConnectionAction: accept` to the `environment` key:

```yml
  ibkr:
    image: ghcr.io/extrange/ibkr:stable
    ports:
      - 6080:6080
      - 8888:8888
    restart: always
    ulimits:
      nofile: 10000
    environment:
      IBC_AcceptIncomingConnectionAction: accept
```
