### ISSUE TITLE
assertion failed [rem_idx != -1]: Unable to find existing allocation for shared memory segment to unmap

### ISSUE THREAD

**Issue by JustinGuese** [extrange/ibkr-docker#77]
just in the past days I'm getting the above error, previously it was working - strange! 

docker compose yaml
```yaml
version: "3"
services:
  ibgateway:
    image: ghcr.io/extrange/ibkr:stable
    platform: linux/amd64
    shm_size: 500m
    container_name: ibgateway
    # restart: unless-stopped
    ulimits:
      nofile: 10000
    environment:
      - USERNAME=xxxx
      - PASSWORD=xxxxxx
      - IBC_TradingMode=paper
      # - IBC_ReadOnlyApi=yes
      - GATEWAY_OR_TWS=gateway
    ports:
      - 6080:6080 # vnc
      - 8888:8888 # api

```

logs 
```
ibgateway  | 2024-01-24 07:25:31:974 IBC:     jts.ini: ApiOnly=true
ibgateway  | 2024-01-24 07:25:31:974 IBC: Starting Gateway
ibgateway  | 
ibgateway  | 
ibgateway  | Navigate to this URL:
ibgateway  | 
ibgateway  |     http://1b0800d336b3:6080/vnc.html?host=1b0800d336b3&port=6080
ibgateway  | 
ibgateway  | Press Ctrl-C to exit
ibgateway  | 
ibgateway  | 
ibgateway  | assertion failed [rem_idx != -1]: Unable to find existing allocation for shared memory segment to unmap
ibgateway  | (VMAllocationTracker.cpp:745 remove_shared_mem)
ibgateway  |  /opt/ibc/scripts/ibcstart.sh: line 504:   226 Trace/breakpoint trap   "$java_path/java" -cp "$ibc_classpath" $java_vm_options$autorestart_option $entry_point "$ibc_ini" "$ib_user_id" "$ib_password" ${mode}
ibgateway  | IBC returned exit status 133
ibgateway  | autorestart file not found
ibgateway  | 
ibgateway  | Gateway finished
ibgateway  | 
ibgateway exited with code 133
```

system:
Mac OS, docker desktop, platform: linux/amd64 mode
