### ISSUE TITLE
Setting localtime

### ISSUE THREAD

**Issue by Dave3991** [extrange/ibkr-docker#79]
this is part of my docker-compose.yaml amd I'm getting error below, did anyone solve it?
Host has right time.

```
  ibkr:
      image: ghcr.io/extrange/ibkr@sha256:905039e3388d10089b9d40bd33303e8eb9c261566f9b82357c0c739b82a236d6 # stable
      ports:
        - "127.0.0.1:6080:6080" # noVNC browser access
        - "127.0.0.1:8880:8888" # API access
      ulimits:
        nofile: 10000 # See FAQ
      environment:
        USERNAME: ${IBKR_USERNAME}
        PASSWORD: ${IBKR_PASSWORD}
      volumes:
        - /etc/localtime:/etc/localtime:ro
      restart: always
```

![image](https://github.com/extrange/ibkr-docker/assets/11957029/5e347e66-3127-416b-bf6d-75d9dbdcc526)
